apiVersion: v1
kind: Secret
metadata:
  name: catalog-secret
  namespace: kongroo
  labels:
    app.kubernetes.io/name: catalog-api
    app.kubernetes.io/instance: catalog-api
    app.kubernetes.io/version: "0.0.4"
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: kongroo
    app.kubernetes.io/managed-by: kubectl
type: Opaque
stringData:
  ConnectionStrings__Database: "Host=postgres;Database=kongroo_catalog;Username=kongroo;Password=replace-with-secure-password"
  Jwt__SigningKey: "replace-with-same-key-as-identity-service"
