// <auto-generated />
using System;
using System.Collections.Generic;
using Kongroo.Catalog.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kongroo.Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260330214011_PersistPromotions")]
    partial class PersistPromotions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kongroo.Catalog.Domain.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("description");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Price", "Kongroo.Catalog.Domain.Game.Price#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("price_currency")
                                .IsFixedLength();
                        });

                    b.HasKey("Id")
                        .HasName("pk_games");

                    b.ToTable("games", "catalog");
                });

            modelBuilder.Entity("Kongroo.Catalog.Domain.Game", b =>
                {
                    b.OwnsMany("Kongroo.Catalog.Domain.Promotion", "Promotions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Discount")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("discount");

                            b1.Property<Guid>("GameId")
                                .HasColumnType("uuid")
                                .HasColumnName("game_id");

                            b1.HasKey("Id")
                                .HasName("pk_promotions");

                            b1.HasIndex("GameId")
                                .HasDatabaseName("ix_promotions_game_id");

                            b1.ToTable("promotions", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("GameId")
                                .HasConstraintName("fk_promotions_games_game_id");

                            b1.OwnsOne("Kongroo.Catalog.Domain.DateTimeRange", "ActiveRange", b2 =>
                                {
                                    b2.Property<Guid>("PromotionId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<DateTimeOffset>("End")
                                        .HasPrecision(0)
                                        .HasColumnType("timestamp(0) with time zone")
                                        .HasColumnName("active_range_end");

                                    b2.Property<DateTimeOffset>("Start")
                                        .HasPrecision(0)
                                        .HasColumnType("timestamp(0) with time zone")
                                        .HasColumnName("active_range_start");

                                    b2.HasKey("PromotionId");

                                    b2.ToTable("promotions", "catalog");

                                    b2.WithOwner()
                                        .HasForeignKey("PromotionId")
                                        .HasConstraintName("fk_promotions_promotions_id");
                                });

                            b1.Navigation("ActiveRange")
                                .IsRequired();
                        });

                    b.Navigation("Promotions");
                });
#pragma warning restore 612, 618
        }
    }
}

