// <auto-generated />
using System;
using System.Collections.Generic;
using Kongroo.Catalog.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kongroo.Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kongroo.BuildingBlocks.Infrastructure.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Error")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("error");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("outbox_messages", "catalog");
                });

            modelBuilder.Entity("Kongroo.Catalog.Domain.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("description");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Price", "Kongroo.Catalog.Domain.Game.Price#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("price_currency")
                                .IsFixedLength();
                        });

                    b.HasKey("Id")
                        .HasName("pk_games");

                    b.ToTable("games", "catalog");
                });

            modelBuilder.Entity("Kongroo.Catalog.Domain.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_id");

                    b.Property<DateTimeOffset>("PurchasedAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("purchased_at");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Total", "Kongroo.Catalog.Domain.Order.Total#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("total_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("total_currency")
                                .IsFixedLength();
                        });

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.ToTable("orders", "catalog");
                });

            modelBuilder.Entity("Kongroo.Catalog.Domain.Game", b =>
                {
                    b.OwnsMany("Kongroo.Catalog.Domain.Promotion", "Promotions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Discount")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("discount");

                            b1.Property<Guid>("GameId")
                                .HasColumnType("uuid")
                                .HasColumnName("game_id");

                            b1.HasKey("Id")
                                .HasName("pk_promotions");

                            b1.HasIndex("GameId")
                                .HasDatabaseName("ix_promotions_game_id");

                            b1.ToTable("promotions", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("GameId")
                                .HasConstraintName("fk_promotions_games_game_id");

                            b1.OwnsOne("Kongroo.Catalog.Domain.DateTimeRange", "ActiveRange", b2 =>
                                {
                                    b2.Property<Guid>("PromotionId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<DateTimeOffset>("End")
                                        .HasPrecision(0)
                                        .HasColumnType("timestamp(0) with time zone")
                                        .HasColumnName("active_range_end");

                                    b2.Property<DateTimeOffset>("Start")
                                        .HasPrecision(0)
                                        .HasColumnType("timestamp(0) with time zone")
                                        .HasColumnName("active_range_start");

                                    b2.HasKey("PromotionId");

                                    b2.ToTable("promotions", "catalog");

                                    b2.WithOwner()
                                        .HasForeignKey("PromotionId")
                                        .HasConstraintName("fk_promotions_promotions_id");
                                });

                            b1.Navigation("ActiveRange")
                                .IsRequired();
                        });

                    b.Navigation("Promotions");
                });

            modelBuilder.Entity("Kongroo.Catalog.Domain.Order", b =>
                {
                    b.OwnsMany("Kongroo.Catalog.Domain.OrderLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid")
                                .HasColumnName("order_id");

                            b1.Property<Guid>("GameId")
                                .HasColumnType("uuid")
                                .HasColumnName("game_id");

                            b1.Property<Guid?>("AppliedPromotionId")
                                .HasColumnType("uuid")
                                .HasColumnName("applied_promotion_id");

                            b1.Property<string>("GameTitle")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("game_title");

                            b1.HasKey("OrderId", "GameId")
                                .HasName("pk_order_lines");

                            b1.ToTable("order_lines", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("OrderId")
                                .HasConstraintName("fk_order_lines_orders_order_id");

                            b1.OwnsOne("Kongroo.Catalog.Domain.Money", "FinalPrice", b2 =>
                                {
                                    b2.Property<Guid>("OrderLineOrderId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("order_id");

                                    b2.Property<Guid>("OrderLineGameId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("game_id");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("final_price_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character(3)")
                                        .HasColumnName("final_price_currency")
                                        .IsFixedLength();

                                    b2.HasKey("OrderLineOrderId", "OrderLineGameId");

                                    b2.ToTable("order_lines", "catalog");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderLineOrderId", "OrderLineGameId")
                                        .HasConstraintName("fk_order_lines_order_lines_order_id_game_id");
                                });

                            b1.OwnsOne("Kongroo.Catalog.Domain.Money", "ListPrice", b2 =>
                                {
                                    b2.Property<Guid>("OrderLineOrderId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("order_id");

                                    b2.Property<Guid>("OrderLineGameId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("game_id");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("list_price_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character(3)")
                                        .HasColumnName("list_price_currency")
                                        .IsFixedLength();

                                    b2.HasKey("OrderLineOrderId", "OrderLineGameId");

                                    b2.ToTable("order_lines", "catalog");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderLineOrderId", "OrderLineGameId")
                                        .HasConstraintName("fk_order_lines_order_lines_order_id_game_id");
                                });

                            b1.Navigation("FinalPrice")
                                .IsRequired();

                            b1.Navigation("ListPrice")
                                .IsRequired();
                        });

                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}

